/**
 * HMRC VAT Flat Rate Scheme sector catalogue.
 *
 * Source: HMRC internal manual FRS7300, "Flat Rate Scheme: sector A to Z".
 * The catalogue was checked against the published table on 2026-07-19. Rates
 * are stored as basis points so the business engines never depend on floats.
 */

export const HMRC_FRS_SECTOR_SOURCE = {
  id: 'hmrc-frs7300-2024-05-31.v1',
  title: 'Flat Rate Scheme: sector A to Z',
  url: 'https://www.gov.uk/hmrc-internal-manuals/vat-flat-rate-scheme/frs7300',
  publishedUpdatedOn: '2024-05-31',
  verifiedOn: '2026-07-19',
  sectorCount: 54,
} as const;

export type FlatRateSector = Readonly<{
  id: string;
  label: string;
  rateBasisPoints: number;
  examples: readonly string[];
}>;

export const HMRC_FRS_SECTORS = [
  {
    id: 'accountancy-or-bookkeeping',
    label: 'Accountancy or bookkeeping',
    rateBasisPoints: 1450,
    examples: ['Accountants', 'Bookkeepers', 'Income tax preparation services'],
  },
  {
    id: 'advertising',
    label: 'Advertising',
    rateBasisPoints: 1100,
    examples: [
      'Advertising consultants',
      'Advertising space providers',
      'Advertising services such as billposting',
    ],
  },
  {
    id: 'agricultural-services',
    label: 'Agricultural services',
    rateBasisPoints: 1100,
    examples: [
      'Services to agriculture such as equipment hire with operator',
      'Animal transport',
      'Animal breeding services',
    ],
  },
  {
    id: 'other-activity',
    label: 'Any other activity that is not listed elsewhere',
    rateBasisPoints: 1200,
    examples: [
      'Coin operated photographic machines',
      'Defence activities',
      'Driving schools',
      'Education',
      'Extraction of peat',
      'Fire and rescue services',
      'Funeral services',
      'Hospitals, nursing homes, medical or dental services',
      'Law and order or judicial activities',
      'Private households',
      'Sewage treatment',
      'Telecommunications',
      'Tour guides',
    ],
  },
  {
    id: 'architect-engineer-or-surveyor',
    label: 'Architect, civil and structural engineer or surveyor',
    rateBasisPoints: 1450,
    examples: [
      'Architects',
      'Civil and structural engineers',
      'Engineering consultants and designers',
      'Quantity surveyors',
      'Surveyors',
      'Town planners',
    ],
  },
  {
    id: 'boarding-or-care-of-animals',
    label: 'Boarding or care of animals',
    rateBasisPoints: 1200,
    examples: [
      'Animal blacksmithing or farrier',
      'Catteries, kennels and stables',
      'Dog walkers',
      'Pet coat clipping',
    ],
  },
  {
    id: 'other-business-services',
    label: 'Business services that are not listed elsewhere',
    rateBasisPoints: 1200,
    examples: [
      'Cleaning services',
      'Credit reporting and collection services',
      'Exhibition and fair organisers',
      'Extermination services',
      'Management activities of holding companies',
      'Market research and opinion pollsters',
      'Research and development',
      'Technical testing and analysis',
    ],
  },
  {
    id: 'catering-restaurants-and-takeaways',
    label: 'Catering services, including restaurants and takeaways',
    rateBasisPoints: 1250,
    examples: [
      'Canteens',
      'Catering',
      'Licensed and unlicensed restaurants and cafés',
      'Sandwich shops',
      'Takeaway food shops and mobile stands',
    ],
  },
  {
    id: 'computer-it-consultancy-or-data-processing',
    label: 'Computer and IT consultancy or data processing',
    rateBasisPoints: 1450,
    examples: [
      'Data processing and database activities',
      'Hardware and software consultants',
      'Software publishing',
    ],
  },
  {
    id: 'computer-repair-services',
    label: 'Computer repair services',
    rateBasisPoints: 1050,
    examples: ['Computer repairs'],
  },
  {
    id: 'waste-or-scrap',
    label: 'Dealing in waste or scrap',
    rateBasisPoints: 1050,
    examples: ['Wholesale of waste and scrap'],
  },
  {
    id: 'entertainment-or-journalism',
    label: 'Entertainment or journalism',
    rateBasisPoints: 1250,
    examples: [
      'Artists and arts facilities',
      'Authors',
      'Dance halls',
      'Dance instruction',
      'Discos',
      'Fairs and amusement parks',
      'Journalists and news agency activities',
      'Live theatre',
    ],
  },
  {
    id: 'estate-agency-or-property-management',
    label: 'Estate agency or property management services',
    rateBasisPoints: 1200,
    examples: ['Estate agency services', 'Property management services'],
  },
  {
    id: 'other-farming-or-agriculture',
    label: 'Farming or agriculture that is not listed elsewhere',
    rateBasisPoints: 650,
    examples: ['Growing of any crops, fruit or animals', 'Wine making from own grown grapes'],
  },
  {
    id: 'film-radio-television-or-video-production',
    label: 'Film, radio, television or video production',
    rateBasisPoints: 1300,
    examples: [
      'Sound, video or computer recording',
      'TV, film, radio or video production, distribution or projection',
    ],
  },
  {
    id: 'financial-services',
    label: 'Financial services',
    rateBasisPoints: 1350,
    examples: [
      'Banks',
      'Building societies',
      'Credit granting',
      'Debt factoring',
      'Financial leasing',
      'Mortgage finance businesses',
    ],
  },
  {
    id: 'forestry-or-fishing',
    label: 'Forestry or fishing',
    rateBasisPoints: 1050,
    examples: ['Fish farms', 'Fish hatcheries', 'Fishing', 'Forestry', 'Logging'],
  },
  {
    id: 'general-building-or-construction',
    label:
      'General building or construction services — use this where materials supplied are 10% or more of turnover',
    rateBasisPoints: 950,
    examples: [
      'Alterations and extensions to commercial or domestic buildings or civil engineering works',
      'Building completion',
      'Earth moving, demolition and landscaping',
      'Electricians',
      'Floor and wall coverings',
      'Glaziers',
      'Joiners or carpenters',
      'Other building equipment installers',
      'Painters',
      'Plasterers',
      'Plumbers',
      'Road, airfield, sports facility and water project building',
      'Roofers',
    ],
  },
  {
    id: 'hairdressing-or-beauty-treatment',
    label: 'Hairdressing or other beauty treatment services',
    rateBasisPoints: 1300,
    examples: ['Beauticians', 'Hairdressers', 'Manicurists', 'Massage parlours', 'Suntan parlours'],
  },
  {
    id: 'hiring-or-renting-goods',
    label: 'Hiring or renting goods',
    rateBasisPoints: 950,
    examples: [
      'Agricultural, construction or civil engineering equipment rental',
      'Car or van rental',
      'Passenger transport rental, including land, water or air',
      'Sporting and recreational equipment rental',
      'TV or video recorders',
      'Video tapes',
    ],
  },
  {
    id: 'hotel-or-accommodation',
    label: 'Hotel or accommodation',
    rateBasisPoints: 1050,
    examples: [
      'Bed and breakfast',
      'Camping and caravan sites',
      'Holiday centres and villages',
      'Licensed or unlicensed hotels or motels with or without restaurants',
      'Self catering accommodation',
      'Youth hostels',
    ],
  },
  {
    id: 'investigation-or-security',
    label: 'Investigation or security',
    rateBasisPoints: 1200,
    examples: ['Detective agencies', 'Security firms for people, sites or items'],
  },
  {
    id: 'labour-only-building-or-construction',
    label:
      'Labour only building or construction services — use this where materials supplied are less than 10% of turnover',
    rateBasisPoints: 1450,
    examples: [
      'Alterations and extensions to commercial or domestic buildings or civil engineering works',
      'Building completion',
      'Earth moving, demolition and landscaping',
      'Electricians',
      'Floor and wall coverings',
      'Glaziers',
      'Joiners or carpenters',
      'Other building equipment installers',
      'Painters',
      'Plasterers',
      'Plumbers',
      'Road, airfield, sports facility and water project building',
      'Roofers',
    ],
  },
  {
    id: 'laundry-or-dry-cleaning',
    label: 'Laundry or dry cleaning services',
    rateBasisPoints: 1200,
    examples: ['Dry cleaning services', 'Launderettes', 'Laundry services'],
  },
  {
    id: 'lawyer-or-legal-services',
    label: 'Lawyer or legal services',
    rateBasisPoints: 1450,
    examples: ['Barristers', 'Injury claims services', 'Solicitors'],
  },
  {
    id: 'library-archive-museum-or-cultural-activity',
    label: 'Library, archive, museum or other cultural activity',
    rateBasisPoints: 950,
    examples: [
      'Archives',
      'Botanical and other gardens',
      'Historical sites and buildings',
      'Libraries',
      'Museums',
      'Nature reserves',
      'Zoos',
    ],
  },
  {
    id: 'management-consultancy',
    label: 'Management consultancy',
    rateBasisPoints: 1400,
    examples: [
      'Business consultancy',
      'Financial consultancy',
      'Management consultancy',
      'Public relations',
    ],
  },
  {
    id: 'manufacturing-fabricated-metal-products',
    label: 'Manufacturing fabricated metal products',
    rateBasisPoints: 1050,
    examples: [
      "Builder's and carpenter's metal products",
      'Containers and tanks, reservoirs, boilers and radiators',
      'Cutlery, tools, locks and hinges',
      'Forging, stamping, pressing or roll forming of metal items',
      'General mechanical engineering',
      'Steam generators',
      'Steel drums and other light metal packaging',
      'Wire products, nails, screws, other fasteners, chains and springs',
    ],
  },
  {
    id: 'manufacturing-food',
    label: 'Manufacturing food',
    rateBasisPoints: 900,
    examples: [
      'Alcoholic beverages',
      'Animal foods',
      'Bakery',
      'Cocoa, chocolate and confectionery',
      'Dairy production',
      'Grain milling',
      'Ice cream',
      'Mineral water and soft drinks',
      'Processing and preservation of fruits and vegetables',
      'Processing of fish',
      'Production and preserving of meat products',
      'Production of edible fats and margarine',
      'Slaughter of animals',
      'Sugar production',
      'Tea and coffee',
    ],
  },
  {
    id: 'other-manufacturing',
    label: 'Manufacturing that is not listed elsewhere',
    rateBasisPoints: 950,
    examples: [
      'Boxes, labels and stationery in paper and cardboard',
      'Collection, purification and distribution of water',
      'Cork, straw, pulp, paper and cardboard production',
      'Extraction of petroleum and natural gas',
      'Furniture',
      'Household, toilet and sanitary goods',
      'Jewellery, coins and medals',
      'Making carpentry items',
      'Pesticides, pharmaceuticals, explosives, man made fibres, rubber, plastic, glass, ceramic, bricks, cement and concrete products',
      'Industrial chemicals, paints, inks, dyes and sealants',
      'Office machinery, electric motors, generators and transformers',
      'Production, distribution and trade in gas or electricity',
      'Refining of metals and making of articles in metal',
      'Saddlery and harness',
      'Sawmilling, planing and impregnation of wood, plywood or veneers',
      'Shoes',
      'Sports goods and toys',
      'Tanning and dressing of leather',
      'Tobacco products',
      'Weapons and ammunition',
      'Wire, measuring and control equipment',
      'Vehicles, ships, motorcycles and aircraft',
      'Carpets',
      'Cut, make and trim',
      'Hats',
      'Knitted or crocheted fabrics',
      'Lace',
      'Leather and fur clothes making',
      'Preparation and spinning of natural and man made fibres',
      'Ribbon',
      'Ropes',
      'Weaving, finishing and manufacture of cloth',
    ],
  },
  {
    id: 'membership-organisation',
    label: 'Membership organisation',
    rateBasisPoints: 800,
    examples: [
      'Business and employers organisations',
      'Political organisations',
      'Professional organisations',
      'Religious organisations',
      'Trade unions',
    ],
  },
  {
    id: 'mining-or-quarrying',
    label: 'Mining or quarrying',
    rateBasisPoints: 1000,
    examples: [
      'Ore or chemical mines, deep or opencast',
      'Quarries for building stone, limestone, gypsum, chalk, slate, sand, gravel, clay or kaolin',
    ],
  },
  {
    id: 'packaging',
    label: 'Packaging',
    rateBasisPoints: 900,
    examples: ['Manufacture, wholesale and retail of packaging'],
  },
  {
    id: 'photography',
    label: 'Photography',
    rateBasisPoints: 1100,
    examples: ['Film processing', 'Portrait or other specialist photography'],
  },
  {
    id: 'post-offices',
    label: 'Post Offices',
    rateBasisPoints: 500,
    examples: ['Post offices', 'Sub-post offices'],
  },
  {
    id: 'printing',
    label: 'Printing',
    rateBasisPoints: 850,
    examples: [
      'Bookbinding',
      'Newspaper, book or periodical printing',
      'Typesetting or master production',
    ],
  },
  {
    id: 'publishing',
    label: 'Publishing',
    rateBasisPoints: 1100,
    examples: ['Books', 'Journals', 'Newspapers', 'Periodicals', 'Sound recordings'],
  },
  {
    id: 'pubs',
    label: 'Pubs',
    rateBasisPoints: 650,
    examples: ['Licensed clubs', 'Public houses however managed'],
  },
  {
    id: 'other-real-estate-activity',
    label: 'Real estate activity that is not listed elsewhere',
    rateBasisPoints: 1400,
    examples: [
      'Buying, development and sale of real estate',
      'Letting of conference or exhibition centres',
      'Letting of own property',
    ],
  },
  {
    id: 'repairing-personal-or-household-goods',
    label: 'Repairing personal or household goods',
    rateBasisPoints: 1000,
    examples: [
      'Repair of boots, shoes, household and electrical goods, watches, clocks or jewellery',
    ],
  },
  {
    id: 'repairing-vehicles',
    label: 'Repairing vehicles',
    rateBasisPoints: 850,
    examples: ['Repair and maintenance of all types of vehicles'],
  },
  {
    id: 'retailing-food-confectionery-tobacco-newspapers-or-childrens-clothing',
    label: "Retailing food, confectionery, tobacco, newspapers or children's clothing",
    rateBasisPoints: 400,
    examples: [
      'Bakers',
      'Butchers',
      "Children's clothes of all types and materials",
      'Confectioners, newsagents and tobacconists',
      'Cookie shops',
      'Delicatessen',
      'Fishmongers',
      'Greengrocers',
      'Grocers',
      'Health foods',
      'Ice cream',
      'Off-licenses',
    ],
  },
  {
    id: 'retailing-pharmaceuticals-medical-goods-cosmetics-or-toiletries',
    label: 'Retailing pharmaceuticals, medical goods, cosmetics or toiletries',
    rateBasisPoints: 800,
    examples: [
      'Cosmetics',
      'Dispensing chemists',
      'Hearing aids',
      'Medical and orthopaedic goods',
      'Toiletries',
    ],
  },
  {
    id: 'other-retailing',
    label: 'Retailing that is not listed elsewhere',
    rateBasisPoints: 750,
    examples: [
      'Adult clothes',
      'Antiques',
      'Art from galleries',
      'Books',
      'Floor coverings',
      'Fur or leather clothes',
      'Furniture',
      'Hardware',
      'Household goods',
      'Lighting',
      'Mail order',
      'Menswear',
      'Mobile telephones',
      'Paints and glass',
      'Photographic equipment',
      'Second hand goods, not cars',
      'Sports goods',
      'Stalls and markets',
      'Stationery',
      'Womenswear',
    ],
  },
  {
    id: 'retailing-vehicles-or-fuel',
    label: 'Retailing vehicles or fuel',
    rateBasisPoints: 650,
    examples: [
      'Filling stations',
      'Motorcycles',
      'Parts and accessories',
      'Wholesale or retail of new or used vehicles',
    ],
  },
  {
    id: 'secretarial-services',
    label: 'Secretarial services',
    rateBasisPoints: 1300,
    examples: ['Secretarial services'],
  },
  {
    id: 'social-work',
    label: 'Social work',
    rateBasisPoints: 1100,
    examples: ['Social work for charities or otherwise, with or without accommodation'],
  },
  {
    id: 'sport-or-recreation',
    label: 'Sport or recreation',
    rateBasisPoints: 850,
    examples: [
      'Betting shops',
      'Casting for theatre, TV or films',
      'Gambling',
      'Ice or roller rinks',
      'Owning of racehorses',
      'Skateboarding parks',
      'Sports arenas and stadia',
    ],
  },
  {
    id: 'transport-or-storage',
    label: 'Transport or storage, including couriers, freight, removals and taxis',
    rateBasisPoints: 1000,
    examples: [
      'Couriers',
      'Excise warehousing',
      'Frozen or refrigerated goods',
      'Furniture removal',
      'Grain',
      'Liquids or gases',
      'Passenger or goods transport by rail, coach, underground, taxi, tram, sea, canal or air',
      'Removing or storing private possessions',
      'Warehousing',
    ],
  },
  {
    id: 'travel-agency',
    label: 'Travel agency',
    rateBasisPoints: 1050,
    examples: [
      'Travel agencies',
      'Travel organisers, excluding those using the Tour Operators Margin Scheme',
    ],
  },
  {
    id: 'veterinary-medicine',
    label: 'Veterinary medicine',
    rateBasisPoints: 1100,
    examples: ['Veterinary activities'],
  },
  {
    id: 'wholesaling-agricultural-products',
    label: 'Wholesaling agricultural products',
    rateBasisPoints: 800,
    examples: [
      'Animal feed',
      'Flowers and plants',
      'Fur, skins and hides',
      'Grain',
      'Live animals',
      'Seeds',
      'Unmanufactured tobacco',
    ],
  },
  {
    id: 'wholesaling-food',
    label: 'Wholesaling food',
    rateBasisPoints: 750,
    examples: [
      'Alcoholic beverages',
      'Coffee, tea and cocoa',
      'Confectionery',
      'Dairy produce',
      'Edible oils and fats',
      'Fish and shellfish',
      'Fruit and vegetables',
      'Game',
      'Juices, mineral waters and soft drinks',
      'Meat and meat products',
      'Poultry and eggs',
      'Tobacco',
    ],
  },
  {
    id: 'other-wholesaling',
    label: 'Wholesaling that is not listed elsewhere',
    rateBasisPoints: 850,
    examples: [
      'Aircraft',
      'Cameras',
      'Cash and carry',
      'Chemicals',
      'China and glassware',
      'Clothing',
      'Food, beverages and tobacco',
      'Footwear',
      'Furniture',
      'Industrial equipment',
      'Jewellery',
      'Machine tools',
      'Machinery',
      'Musical instruments',
      'Office equipment',
      'Pharmaceuticals',
      'Records, tapes, CDs and videos',
      'Ships and boats',
      'Toys and games',
    ],
  },
] as const satisfies readonly FlatRateSector[];

export function findFlatRateSector(id: string | undefined): FlatRateSector | undefined {
  if (id === undefined) return undefined;
  return HMRC_FRS_SECTORS.find((sector) => sector.id === id);
}

export function searchFlatRateSectors(query: string): readonly FlatRateSector[] {
  const words = normaliseSearch(query).split(' ').filter(Boolean);
  if (words.length === 0) return HMRC_FRS_SECTORS;
  return HMRC_FRS_SECTORS.filter((sector) => {
    const haystack = normaliseSearch([sector.label, ...sector.examples].join(' '));
    return words.every((word) => haystack.includes(word));
  });
}

function normaliseSearch(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, ' ')
    .trim();
}
