/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 48be00b2a974080b3b31b59e886414d8)
interface __BaseEnv_CloudflareBindings {
	METER_KV: KVNamespace;
	OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1";
	OPENROUTER_MODEL: "google/gemini-2.5-flash-lite";
	PHRASE_DAILY_CAP: "2000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_BASE_URL" | "OPENROUTER_MODEL" | "PHRASE_DAILY_CAP">> {}
}
