import type { ConfigContext, ExpoConfig } from 'expo/config';

function clerkPublishableKeyForBuild(): string | undefined {
  const key = process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY?.trim();
  if (!key) return undefined;
  if (process.env.NODE_ENV === 'production' && !key.startsWith('pk_live_')) {
    throw new Error(
      'Production Melo builds require an EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY beginning with pk_live_.',
    );
  }
  return key;
}

function businessBetaFlagForBuild(): 'true' | 'false' {
  return process.env.EXPO_PUBLIC_MELO_BUSINESS_BETA?.trim() === 'true' ? 'true' : 'false';
}

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  // The public app identity is Melo. The EAS slug remains the existing project slug, while the
  // reverse-DNS identifiers use the Melo domains owned by the publisher. "folio" remains only as
  // a compatibility deep-link scheme for pre-release owner builds.
  name: 'Melo',
  slug: 'folio-v2-greenfield',
  scheme: ['melo', 'folio'],
  version: '1.0.0',
  icon: './assets/canonical/favicon.png',
  orientation: 'portrait',
  platforms: ['ios', 'android'],
  userInterfaceStyle: 'automatic',
  runtimeVersion: {
    policy: 'appVersion',
  },
  updates: {
    // OTA JS updates via EAS Update (enabled 2026-07-05). Non-blocking check on launch
    // (fallbackToCacheTimeout 0): users never wait on the network, a fetched update applies on
    // the NEXT launch. Locally-built APKs pin the 'production' channel via requestHeaders;
    // EAS-built profiles get their channel from eas.json. Native/config changes still need a
    // full rebuild — runtimeVersion (appVersion policy) fences incompatible updates.
    enabled: true,
    url: 'https://u.expo.dev/ef69039d-abaf-48e9-b35a-52d80b03a96a',
    fallbackToCacheTimeout: 0,
    requestHeaders: {
      'expo-channel-name': 'production',
    },
  },
  ios: {
    ...config.ios,
    bundleIdentifier: 'com.melomoney.app',
    buildNumber: '1',
    infoPlist: {
      ...config.ios?.infoPlist,
      NSFaceIDUsageDescription: 'Melo uses device authentication to lock local money data.',
    },
    supportsTablet: false,
    associatedDomains: ['applinks:melo-money.com'],
  },
  android: {
    ...config.android,
    adaptiveIcon: {
      foregroundImage: './assets/canonical/favicon-maskable.png',
      backgroundColor: '#F6F4EE',
    },
    allowBackup: false,
    blockedPermissions: [
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.RECORD_AUDIO',
      'android.permission.SYSTEM_ALERT_WINDOW',
      'android.permission.WRITE_EXTERNAL_STORAGE',
    ],
    package: 'com.melomoney.app',
    versionCode: 1,
    intentFilters: [
      {
        action: 'VIEW',
        autoVerify: true,
        category: ['BROWSABLE', 'DEFAULT'],
        data: [{ scheme: 'https', host: 'melo-money.com', pathPrefix: '/open' }],
      },
    ],
  },
  plugins: [
    'expo-router',
    'expo-secure-store',
    'expo-web-browser',
    [
      'expo-audio',
      {
        enableBackgroundPlayback: false,
        enableBackgroundRecording: false,
        microphonePermission: false,
        recordAudioAndroid: false,
      },
    ],
    'expo-iap',
    '@sentry/react-native',
    './plugins/withUploadSigning.cjs',
    [
      // R8 code + resource shrinking for release builds (the 68MB sideload APK problem).
      // If a release build ever crashes on boot after a new native dep, suspect missing
      // ProGuard keep rules first. extraProguardRules is the DURABLE home for keep rules —
      // android/app/proguard-rules.pro is gitignored and regenerated by `expo prebuild`, so
      // rules that only live there are lost on a clean prebuild/EAS build. Libraries that ship
      // their own consumer ProGuard rules (bundled in their AAR) do NOT need an entry here —
      // R8 merges those automatically. Verified at plan 110 time (2026-07-11): Clerk
      // (@clerk/clerk-expo) has no android/ dir — JS-only, nothing to keep. Sentry
      // (@sentry/react-native) ships no consumer rules in its own android/ module locally, but
      // its underlying io.sentry:sentry-android Maven dependency is documented
      // ProGuard/R8-friendly and embeds its own consumer rules — no manual rule needed.
      'expo-build-properties',
      {
        android: {
          minSdkVersion: 29,
          enableProguardInReleaseBuilds: true,
          enableShrinkResourcesInReleaseBuilds: true,
          extraProguardRules: `
# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# expo-iap (verified package prefix: expo.modules.iap, no consumer rules shipped)
-keep class expo.modules.iap.** { *; }

# react-native-android-widget (verified package prefix: com.reactnativeandroidwidget, no consumer rules shipped)
-keep class com.reactnativeandroidwidget.** { *; }
`,
        },
        ios: {
          // Expo 56's native dependency floor is 16.4; this satisfies the frozen iOS 16+ policy.
          deploymentTarget: '16.4',
        },
      },
    ],
    [
      // Small-icon tint uses the brand's calm terracotta — visible on the shade without
      // reading as an alert color. No dedicated monochrome icon asset yet; falls back to
      // the app icon until one is drawn.
      'expo-notifications',
      {
        color: '#DC5E33',
        defaultChannel: 'melo',
      },
    ],
    [
      'react-native-android-widget',
      {
        widgets: [
          {
            name: 'SafeZoneWidget', // must match SAFE_ZONE_WIDGET_NAME in widget/widgetSnapshotWriter.tsx
            label: 'Melo — Safe Zone',
            description: 'See how much you can safely spend today, at a glance.',
            minWidth: '110dp',
            minHeight: '40dp',
            targetCellWidth: 4,
            targetCellHeight: 1,
            maxResizeWidth: '250dp',
            maxResizeHeight: '110dp',
            resizeMode: 'horizontal|vertical',
            updatePeriodMillis: 1800000,
          },
        ],
      },
    ],
    [
      'expo-splash-screen',
      {
        backgroundColor: '#F6F4EE',
        image: './assets/canonical/splash.png',
        imageWidth: 120,
        dark: {
          backgroundColor: '#1B1613',
          image: './assets/canonical/splash.png',
        },
      },
    ],
    [
      'expo-image-picker',
      {
        photosPermission:
          'Melo reads only the statement image you choose on this device. Nothing is added until you review it.',
        cameraPermission: false,
      },
    ],
    'expo-sharing',
  ],
  experiments: {
    typedRoutes: true,
  },
  extra: {
    ...config.extra,
    eas: {
      projectId: 'ef69039d-abaf-48e9-b35a-52d80b03a96a',
    },
    publicUrls: {
      website: 'https://melo-money.com',
      open: 'https://melo-money.com/open',
      privacy: 'https://melo-money.com/privacy',
      terms: 'https://melo-money.com/terms',
      support: 'https://melo-money.com/support',
      supportEmail: 'support@melo-money.com',
    },
    // Clerk PUBLISHABLE key (public by design). There is no
    // hardcoded development fallback: signed-out Melo remains fully usable, while production
    // builds reject pk_test_* so a store binary cannot silently target a development instance.
    // The secret key never exists anywhere in this repo or app.
    EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY: clerkPublishableKeyForBuild(),
    // Optional zero-knowledge backup service. The server authenticates the Clerk account and stores
    // only the client-encrypted envelope; the separate recovery code never leaves the device.
    EXPO_PUBLIC_MELO_CLOUD_VAULT_URL:
      process.env.EXPO_PUBLIC_MELO_CLOUD_VAULT_URL ??
      'https://melo-cloud-vault.tgdroppin.workers.dev',
    // Optional UK Open Banking adapter. Provider credentials and per-user provider connection
    // identifiers stay in the Worker; the app receives only provider-neutral consent/account state
    // and staged transaction candidates.
    EXPO_PUBLIC_MELO_OPEN_BANKING_URL:
      process.env.EXPO_PUBLIC_MELO_OPEN_BANKING_URL ??
      'https://melo-open-banking.tgdroppin.workers.dev',
    // Google Play purchase verification. The private Play/service and Ed25519 signing keys stay
    // in the Worker; the APK contains only this endpoint and the public verification key.
    EXPO_PUBLIC_MELO_BILLING_URL:
      process.env.EXPO_PUBLIC_MELO_BILLING_URL ??
      'https://melo-billing-entitlements.tgdroppin.workers.dev',
    EXPO_PUBLIC_MELO_BILLING_ENTITLEMENT_PUBLIC_KEY:
      process.env.EXPO_PUBLIC_MELO_BILLING_ENTITLEMENT_PUBLIC_KEY ??
      'OKponTUZ9ZP1APZpvUeUK5BmKmlJm8FZQ5IDAd92HL8',
    // Build-distributed exposure gate. This may become true only after RB-BUSINESS-TAX-BETA is
    // explicitly closed and the root/EAS checker passes; existing Business workspaces are never
    // hidden by this creation-only flag.
    EXPO_PUBLIC_MELO_BUSINESS_BETA: businessBetaFlagForBuild(),
    // Sentry DSN — public submit-only key (crash reports; privacy-tuned init lives in
    // src/folio/lib/errorReporting.ts: no PII, no screenshots, no tracing).
    EXPO_PUBLIC_SENTRY_DSN:
      process.env.EXPO_PUBLIC_SENTRY_DSN ??
      'https://4593a25966a06219730d6509c801febf@o4511684285497344.ingest.de.sentry.io/4511684377641040',
  },
});
